### ISSUE TITLE
Support for Reading Binary File into Buffer

### ISSUE THREAD

**Issue by abramjstamper** [Pupix/binary-buffer-parser#2]
Do you have any support for reading in the binary file as a buffer of specified length? I tried to use the _private_ function `._read`. However, I wasn't able to get it working since I didn't have a type specified in your dictionary.

**Comment by Pupix** [comment]
Do you mean creating a plain Buffer instance with contents of the file or a chunk of it? No.

If you got the whole file loaded in memory then you can just use [Buffer.slice](https://nodejs.org/api/buffer.html#buffer_buf_slice_start_end) otherwise you can use [read-chunk](https://www.npmjs.com/package/read-chunk)
